#!/bin/bash

# 🚀 MELSU Portal - Скрипт управления сервисами
# Автор: Sasha Honcharov (sanumxxx@yandex.ru)

# Цвета для вывода
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Пути
PROJECT_PATH="/var/www/melsu"
BACKEND_PATH="$PROJECT_PATH/backend"
FRONTEND_PATH="$PROJECT_PATH/frontend"

# Функции для логирования
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

log_step() {
    echo -e "${PURPLE}[STEP]${NC} $1"
}

log_debug() {
    echo -e "${CYAN}[DEBUG]${NC} $1"
}

# Функция проверки статуса сервиса
check_service_status() {
    local service=$1
    if systemctl is-active --quiet $service; then
        echo -e "${GREEN}✅ $service - активен${NC}"
    else
        echo -e "${RED}❌ $service - неактивен${NC}"
    fi
}

# Функция проверки здоровья API
check_api_health() {
    local response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/health 2>/dev/null)
    if [ "$response" = "200" ]; then
        echo -e "${GREEN}✅ API health check - OK${NC}"
    else
        echo -e "${RED}❌ API health check - FAILED (код: $response)${NC}"
    fi
}

# Функция проверки подключения к БД
check_database() {
    log_step "Проверка подключения к базе данных..."
    sudo -u postgres psql melsu_db -c "SELECT 1;" > /dev/null 2>&1
    if [ $? -eq 0 ]; then
        echo -e "${GREEN}✅ База данных - доступна${NC}"
    else
        echo -e "${RED}❌ База данных - недоступна${NC}"
    fi
}

# Функция диагностики миграций
diagnose_migrations() {
    log_step "Диагностика состояния миграций..."
    cd $BACKEND_PATH
    
    echo -e "\n${CYAN}=== ДИАГНОСТИКА МИГРАЦИЙ ===${NC}"
    
    # Получаем текущую ревизию
    log_debug "Текущая ревизия в БД:"
    local current_output=$(sudo -u melsu $BACKEND_PATH/venv/bin/alembic current 2>&1)
    echo "$current_output"
    
    # Получаем все head ревизии
    log_debug "Head ревизии:"
    local heads_output=$(sudo -u melsu $BACKEND_PATH/venv/bin/alembic heads 2>&1)
    echo "$heads_output"
    
    # Считаем количество head ревизий
    local heads_count=$(echo "$heads_output" | grep -c "^[a-f0-9]\{12\}")
    log_debug "Количество head ревизий: $heads_count"
    
    # Показываем историю миграций
    log_debug "История миграций (последние 10):"
    sudo -u melsu $BACKEND_PATH/venv/bin/alembic history -r-10: 2>/dev/null || echo "Не удалось получить историю"
    
    # Проверяем на конфликты
    if [ $heads_count -gt 1 ]; then
        log_warning "⚠️  Обнаружен конфликт миграций: найдено $heads_count head ревизий"
        echo -e "${YELLOW}Head ревизии:${NC}"
        echo "$heads_output" | grep "^[a-f0-9]\{12\}"
        return 1
    elif [ $heads_count -eq 1 ]; then
        log_success "✅ Конфликтов миграций не обнаружено"
        return 0
    else
        log_error "❌ Не удалось определить состояние миграций"
        return 2
    fi
}

# Функция исправления конфликтов миграций
fix_migration_conflicts() {
    log_step "Исправление конфликтов миграций..."
    cd $BACKEND_PATH
    
    # Сначала диагностируем
    local heads_output=$(sudo -u melsu $BACKEND_PATH/venv/bin/alembic heads 2>&1)
    local heads_count=$(echo "$heads_output" | grep -c "^[a-f0-9]\{12\}")
    
    if [ $heads_count -le 1 ]; then
        log_info "Конфликтов миграций не обнаружено"
        return 0
    fi
    
    log_warning "Обнаружено $heads_count head ревизий. Исправляю..."
    
    # Получаем список head ревизий
    local heads=$(echo "$heads_output" | grep "^[a-f0-9]\{12\}" | cut -d' ' -f1)
    log_debug "Head ревизии для объединения: $(echo $heads | tr '\n' ' ')"
    
    # Создаем merge ревизию
    log_info "Создаю merge ревизию для объединения head ревизий..."
    local merge_output=$(sudo -u melsu $BACKEND_PATH/venv/bin/alembic merge heads -m "Merge multiple heads - auto-generated by melsu_control" 2>&1)
    
    if [ $? -eq 0 ]; then
        log_success "✅ Merge ревизия успешно создана"
        echo "$merge_output"
        
        # Применяем новую merge ревизию
        log_info "Применяю merge ревизию..."
        sudo -u melsu $BACKEND_PATH/venv/bin/alembic upgrade head
        
        if [ $? -eq 0 ]; then
            log_success "✅ Конфликт миграций успешно исправлен"
            return 0
        else
            log_error "❌ Ошибка при применении merge ревизии"
            return 1
        fi
    else
        log_error "❌ Ошибка при создании merge ревизии:"
        echo "$merge_output"
        return 1
    fi
}

# Улучшенная функция применения миграций
apply_migrations() {
    log_step "Применение миграций базы данных..."
    cd $BACKEND_PATH
    
    # Сначала проверяем на конфликты
    log_debug "Проверка на конфликты миграций..."
    local heads_output=$(sudo -u melsu $BACKEND_PATH/venv/bin/alembic heads 2>&1)
    local heads_count=$(echo "$heads_output" | grep -c "^[a-f0-9]\{12\}")
    
    if [ $heads_count -gt 1 ]; then
        log_warning "Обнаружен конфликт миграций. Исправляю автоматически..."
        fix_migration_conflicts
        if [ $? -ne 0 ]; then
            log_error "Не удалось исправить конфликт миграций"
            return 1
        fi
    fi
    
    # Получаем информацию о миграциях
    log_debug "Получение информации о текущих миграциях..."
    local current_output=$(sudo -u melsu $BACKEND_PATH/venv/bin/alembic current 2>&1)
    echo "Текущая ревизия: $current_output"
    
    local heads_output=$(sudo -u melsu $BACKEND_PATH/venv/bin/alembic heads 2>&1)
    echo "Head ревизия: $heads_output"
    
    # Проверяем наличие новых миграций
    local current_rev=$(echo "$current_output" | grep -o '[a-f0-9]\{12\}' | head -1)
    local head_rev=$(echo "$heads_output" | grep -o '[a-f0-9]\{12\}' | head -1)
    
    if [ -z "$current_rev" ]; then
        log_warning "Текущая ревизия не определена. Возможно, БД пустая."
        current_rev="empty"
    fi
    
    if [ -z "$head_rev" ]; then
        log_error "Не удалось определить head ревизию"
        return 1
    fi
    
    if [ "$current_rev" != "$head_rev" ]; then
        log_info "Обнаружены новые миграции. Применяю..."
        log_debug "Текущая: $current_rev, Head: $head_rev"
        
        # Показываем, какие миграции будут применены
        log_debug "Миграции для применения:"
        sudo -u melsu $BACKEND_PATH/venv/bin/alembic history -r$current_rev:head 2>/dev/null || echo "Не удалось получить список миграций"
        
        # Применяем миграции
        local upgrade_output=$(sudo -u melsu $BACKEND_PATH/venv/bin/alembic upgrade head 2>&1)
        if [ $? -eq 0 ]; then
            log_success "✅ Миграции успешно применены"
            echo "$upgrade_output"
        else
            log_error "❌ Ошибка при применении миграций:"
            echo "$upgrade_output"
            return 1
        fi
    else
        log_info "✅ Все миграции уже применены (ревизия: $current_rev)"
    fi
}

# Функция резервного копирования БД
backup_database() {
    log_step "Создание резервной копии базы данных..."
    local backup_dir="/var/backups/melsu"
    local backup_file="$backup_dir/melsu_db_$(date +%Y%m%d_%H%M%S).sql"
    
    mkdir -p $backup_dir
    sudo -u postgres pg_dump melsu_db > $backup_file
    
    if [ $? -eq 0 ]; then
        log_success "Резервная копия создана: $backup_file"
        
        # Удаляем старые бэкапы (старше 7 дней)
        find $backup_dir -name "melsu_db_*.sql" -mtime +7 -delete
    else
        log_error "Ошибка создания резервной копии"
        return 1
    fi
}

# Функция обновления проекта
update_project() {
    log_step "Обновление проекта из Git репозитория..."
    
    # Создаем бэкап перед обновлением
    backup_database
    
    cd $PROJECT_PATH
    
    # Проверяем наличие изменений
    git fetch origin main
    local local_commit=$(git rev-parse HEAD)
    local remote_commit=$(git rev-parse origin/main)
    
    if [ "$local_commit" = "$remote_commit" ]; then
        log_info "Проект уже актуален"
        return 0
    fi
    
    log_info "Обнаружены обновления. Загружаю изменения..."
    git pull origin main
    
    if [ $? -ne 0 ]; then
        log_error "Ошибка при загрузке обновлений"
        return 1
    fi
    
    # Обновляем backend
    log_step "Обновление backend зависимостей..."
    cd $BACKEND_PATH
    sudo -u melsu $BACKEND_PATH/venv/bin/pip install -r requirements.txt
    
    # Применяем миграции
    apply_migrations
    
    # Обновляем frontend
    log_step "Обновление и сборка frontend..."
    cd $FRONTEND_PATH
    sudo -u melsu npm install
    sudo -u melsu npm run build
    
    log_success "Проект успешно обновлен"
}

# Функция безопасного перезапуска
safe_restart() {
    log_step "Безопасный перезапуск сервисов..."
    
    # Проверяем, что все готово к перезапуску
    if ! systemctl is-active --quiet postgresql; then
        log_error "PostgreSQL не запущен. Запускаю..."
        systemctl start postgresql
    fi
    
    if ! systemctl is-active --quiet redis-server; then
        log_error "Redis не запущен. Запускаю..."
        systemctl start redis-server
    fi
    
    # Перезапускаем сервисы по порядку
    log_info "Перезапуск Celery Worker..."
    systemctl restart melsu-worker
    
    log_info "Перезапуск API..."
    systemctl restart melsu-api
    
    # Ждем, пока API запустится
    log_info "Ожидание запуска API..."
    sleep 5
    
    # Проверяем здоровье API
    local retries=0
    while [ $retries -lt 10 ]; do
        if curl -s http://localhost:8000/health > /dev/null; then
            break
        fi
        sleep 2
        retries=$((retries + 1))
    done
    
    log_info "Перезапуск Nginx..."
    systemctl restart nginx
    
    log_success "Сервисы перезапущены"
}

# Функция полного исправления миграций с использованием комплексного скрипта
fix_migrations_complete() {
    log_step "Запуск полного исправления миграций..."
    
    # Проверяем наличие скрипта исправления
    local fix_script="$BACKEND_PATH/fix_migrations_complete.sh"
    if [ ! -f "$fix_script" ]; then
        log_error "Скрипт исправления миграций не найден: $fix_script"
        log_info "Создаю скрипт исправления миграций..."
        
        # Создаем скрипт если его нет
        cat > "$fix_script" << 'EOF'
#!/bin/bash

# Полное исправление конфликтов миграций
# Автоматически создано melsu_control.sh

set -e

echo "🔧 Полное исправление миграций MELSU Portal"
echo "==========================================="

# Остановка сервисов
echo "⏹️ Остановка сервисов..."
systemctl stop melsu-api melsu-worker

# Переход в директорию backend
cd /var/www/melsu/backend

# Создание резервной копии
echo "💾 Создание резервной копии БД..."
mkdir -p /var/backups/melsu
sudo -u postgres pg_dump melsu_db > /var/backups/melsu/melsu_db_before_migration_fix_$(date +%Y%m%d_%H%M%S).sql

# Удаление проблемных merge ревизий
echo "🗑️ Удаление проблемных merge ревизий..."
find alembic/versions/ -name "*merge*" -type f -delete 2>/dev/null || true
find alembic/versions/ -name "*ad3c0d6caa7f*" -type f -delete 2>/dev/null || true

# Очистка истории миграций
echo "🧹 Очистка истории миграций..."
sudo -u postgres psql melsu_db -c "DELETE FROM alembic_version;" 2>/dev/null || true

# Проверка и добавление отсутствующих полей
echo "🔍 Проверка структуры БД..."
sudo -u postgres psql melsu_db -c "
DO \$\$
BEGIN
    -- Добавляем faculty_id если не существует
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='user_profiles' AND column_name='faculty_id') THEN
        ALTER TABLE user_profiles ADD COLUMN faculty_id INTEGER;
        ALTER TABLE user_profiles ADD CONSTRAINT fk_user_profiles_faculty_id FOREIGN KEY (faculty_id) REFERENCES departments(id);
        RAISE NOTICE 'Добавлено поле faculty_id';
    END IF;
    
    -- Добавляем department_id если не существует
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='user_profiles' AND column_name='department_id') THEN
        ALTER TABLE user_profiles ADD COLUMN department_id INTEGER;
        ALTER TABLE user_profiles ADD CONSTRAINT fk_user_profiles_department_id FOREIGN KEY (department_id) REFERENCES departments(id);
        RAISE NOTICE 'Добавлено поле department_id';
    END IF;
END
\$\$;
" || echo "Предупреждение: Не удалось проверить/добавить поля"

# Определение правильной ревизии
echo "🎯 Определение текущей ревизии..."
if sudo -u postgres psql melsu_db -c "SELECT 1 FROM information_schema.columns WHERE table_name='user_profiles' AND column_name='faculty_id';" | grep -q "1 row"; then
    echo "Поля faculty_id и department_id найдены, устанавливаю ревизию d34404f8ec53"
    sudo -u postgres psql melsu_db -c "INSERT INTO alembic_version (version_num) VALUES ('d34404f8ec53');"
else
    echo "Поля faculty_id и department_id не найдены, устанавливаю ревизию a7843b1b03ca"
    sudo -u postgres psql melsu_db -c "INSERT INTO alembic_version (version_num) VALUES ('a7843b1b03ca');"
fi

# Применение оставшихся миграций
echo "📦 Применение миграций..."
sudo -u melsu /var/www/melsu/backend/venv/bin/alembic upgrade head

# Инициализация данных
echo "🔄 Инициализация системных данных..."
sudo -u melsu /var/www/melsu/backend/venv/bin/python -c "
import sys
sys.path.append('/var/www/melsu/backend')
from app.startup import init_departments, init_roles, init_request_templates
from app.database import get_db
from sqlalchemy.orm import Session

# Получаем сессию БД
db = next(get_db())

try:
    print('Инициализация департаментов...')
    init_departments(db)
    
    print('Инициализация ролей...')
    init_roles(db)
    
    print('Инициализация шаблонов заявок...')
    init_request_templates(db)
    
    db.commit()
    print('✅ Инициализация завершена успешно')
except Exception as e:
    db.rollback()
    print(f'❌ Ошибка инициализации: {e}')
    raise
finally:
    db.close()
"

# Запуск сервисов
echo "🚀 Запуск сервисов..."
systemctl start melsu-api melsu-worker

# Проверка статуса
echo "✅ Исправление миграций завершено!"
echo "Проверяю статус сервисов..."
sleep 5
systemctl status melsu-api --no-pager -l
systemctl status melsu-worker --no-pager -l

echo "🎉 Все готово!"
EOF

        chmod +x "$fix_script"
        chown melsu:melsu "$fix_script"
        log_success "Скрипт исправления миграций создан"
    fi
    
    # Запускаем скрипт исправления
    log_info "Запуск скрипта полного исправления миграций..."
    bash "$fix_script"
    
    if [ $? -eq 0 ]; then
        log_success "✅ Полное исправление миграций завершено успешно"
        
        # Проверяем состояние после исправления
        log_info "Проверка состояния после исправления..."
        diagnose_migrations
    else
        log_error "❌ Ошибка при выполнении полного исправления миграций"
        return 1
    fi
}

# Функция инициализации системы управления доступом к справочникам
init_directory_access_system() {
    log_step "Инициализация системы управления доступом к справочникам..."
    
    # Создаем резервную копию перед инициализацией
    log_info "Создание резервной копии БД..."
    backup_database
    
    # Проверяем и создаем таблицы
    log_info "Проверка и создание таблиц directory_access..."
    sudo -u postgres psql melsu_db << 'EOF'
-- Создаем таблицу directory_access_template
CREATE TABLE IF NOT EXISTS directory_access_template (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    access_type VARCHAR(10) NOT NULL CHECK (access_type IN ('READ', 'write', 'admin')),
    scope VARCHAR(20) NOT NULL CHECK (scope IN ('students', 'groups', 'departments', 'all')),
    allows_inheritance BOOLEAN DEFAULT FALSE,
    inherit_children BOOLEAN DEFAULT TRUE,
    is_global BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE,
    for_roles JSONB,
    department_types JSONB,
    restrictions JSONB,
    created_by INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Создаем таблицу directory_access
CREATE TABLE IF NOT EXISTS directory_access (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    department_id INTEGER REFERENCES departments(id) ON DELETE CASCADE,
    access_type VARCHAR(10) NOT NULL CHECK (access_type IN ('read', 'write', 'admin')),
    scope VARCHAR(20) NOT NULL CHECK (scope IN ('students', 'groups', 'departments', 'all')),
    allows_inheritance BOOLEAN DEFAULT FALSE,
    inherit_children BOOLEAN DEFAULT TRUE,
    restrictions JSONB DEFAULT '{}',
    description TEXT,
    expires_at TIMESTAMP,
    is_active BOOLEAN DEFAULT TRUE,
    granted_by INTEGER REFERENCES users(id),
    granted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    template_id INTEGER REFERENCES directory_access_template(id) ON DELETE SET NULL
);

-- Создаем индексы для производительности
CREATE INDEX IF NOT EXISTS idx_directory_access_user_id ON directory_access(user_id);
CREATE INDEX IF NOT EXISTS idx_directory_access_department_id ON directory_access(department_id);
CREATE INDEX IF NOT EXISTS idx_directory_access_scope ON directory_access(scope);
CREATE INDEX IF NOT EXISTS idx_directory_access_expires_at ON directory_access(expires_at);
CREATE INDEX IF NOT EXISTS idx_directory_access_is_active ON directory_access(is_active);
CREATE INDEX IF NOT EXISTS idx_directory_access_template_name ON directory_access_template(name);
CREATE INDEX IF NOT EXISTS idx_directory_access_template_is_active ON directory_access_template(is_active);
EOF

    if [ $? -eq 0 ]; then
        log_success "✅ Таблицы directory_access созданы успешно"
    else
        log_error "❌ Ошибка создания таблиц directory_access"
        return 1
    fi
    
    # Предоставляем права доступа
    log_info "Предоставление прав доступа пользователю melsu_user..."
    sudo -u postgres psql melsu_db << 'EOF'
-- Предоставляем права на таблицы directory_access
GRANT SELECT, INSERT, UPDATE, DELETE ON directory_access TO melsu_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON directory_access_template TO melsu_user;

-- Предоставляем права на последовательности (для автоинкремента)
GRANT USAGE, SELECT ON SEQUENCE directory_access_id_seq TO melsu_user;
GRANT USAGE, SELECT ON SEQUENCE directory_access_template_id_seq TO melsu_user;

-- Предоставляем права на все таблицы и последовательности
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO melsu_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO melsu_user;

-- Устанавливаем права по умолчанию для новых объектов
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO melsu_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO melsu_user;
EOF

    if [ $? -eq 0 ]; then
        log_success "✅ Права доступа предоставлены успешно"
    else
        log_error "❌ Ошибка предоставления прав доступа"
        return 1
    fi
    
    # Создаем шаблоны доступа
    log_info "Создание шаблонов доступа..."
    sudo -u postgres psql melsu_db << 'EOF'
-- Удаляем старые шаблоны (если есть) и создаем новые
DELETE FROM directory_access_template;

-- Вставляем шаблоны доступа
INSERT INTO directory_access_template (name, description, access_type, scope, allows_inheritance, inherit_children, is_global, is_active) VALUES
('Работник факультета', 'Доступ для работников факультета ко всем данным подчиненных подразделений', 'read', 'all', true, true, false, true),
('Работник кафедры', 'Доступ для работников кафедры к данным своего подразделения', 'read', 'all', true, true, false, true),
('Куратор группы', 'Доступ куратора к студентам своей группы', 'read', 'students', false, false, false, true),
('Декан факультета', 'Полный доступ декана к данным факультета', 'admin', 'all', true, true, false, true),
('Заведующий кафедрой', 'Полный доступ заведующего к данным кафедры', 'admin', 'all', true, true, false, true),
('Сотрудник учебного отдела', 'Доступ к редактированию данных студентов и групп', 'write', 'all', false, false, true, true),
('Супервизор справочников', 'Полный доступ к управлению справочниками', 'admin', 'all', false, false, true, true),
('Секретарь факультета', 'Доступ к просмотру и редактированию данных студентов факультета', 'write', 'students', true, true, false, true),
('Методист кафедры', 'Доступ к просмотру данных студентов и групп кафедры', 'read', 'students', true, true, false, true),
('Администратор системы', 'Полный доступ ко всем справочникам системы', 'admin', 'all', false, false, true, true);

-- Проверяем количество созданных шаблонов
SELECT COUNT(*) as template_count FROM directory_access_template;
EOF

    if [ $? -eq 0 ]; then
        log_success "✅ Шаблоны доступа созданы успешно"
    else
        log_error "❌ Ошибка создания шаблонов доступа"
        return 1
    fi
    
    # Проверяем создание директории admin для API
    log_info "Проверка структуры API..."
    mkdir -p $BACKEND_PATH/app/api/admin
    touch $BACKEND_PATH/app/api/admin/__init__.py
    chown -R melsu:melsu $BACKEND_PATH/app/api/admin
    
    # Исправляем состояние alembic
    log_info "Исправление состояния alembic..."
    cd $BACKEND_PATH
    sudo -u melsu $BACKEND_PATH/venv/bin/alembic stamp head
    
    if [ $? -eq 0 ]; then
        log_success "✅ Состояние alembic исправлено"
    else
        log_warning "⚠️  Предупреждение: Не удалось исправить состояние alembic"
    fi
    
    # Инициализируем системные данные
    log_info "Инициализация системных данных..."
    sudo -u melsu $BACKEND_PATH/venv/bin/python -c "
import sys
sys.path.append('$BACKEND_PATH')
try:
    from app.startup import init_departments, init_roles, init_request_templates
    from app.database import get_db
    from sqlalchemy.orm import Session
    
    # Получаем сессию БД
    db = next(get_db())
    
    try:
        print('Инициализация департаментов...')
        init_departments(db)
        
        print('Инициализация ролей...')
        init_roles(db)
        
        print('Инициализация шаблонов заявок...')
        init_request_templates(db)
        
        db.commit()
        print('✅ Системные данные инициализированы успешно')
    except Exception as e:
        db.rollback()
        print(f'❌ Ошибка инициализации системных данных: {e}')
        raise
    finally:
        db.close()
except Exception as e:
    print(f'❌ Ошибка при инициализации: {e}')
    exit(1)
"
    
    # Проверяем результат инициализации
    log_info "Проверка результата инициализации..."
    local table_count=$(sudo -u postgres psql melsu_db -t -c "SELECT COUNT(*) FROM information_schema.tables WHERE table_name IN ('directory_access', 'directory_access_template');")
    local template_count=$(sudo -u postgres psql melsu_db -t -c "SELECT COUNT(*) FROM directory_access_template WHERE is_active = true;" 2>/dev/null || echo "0")
    
    if [ "$table_count" -eq 2 ] && [ "$template_count" -gt 0 ]; then
        log_success "✅ Система управления доступом к справочникам инициализирована успешно!"
        log_info "📊 Создано таблиц: 2"
        log_info "📋 Создано шаблонов доступа: $template_count"
        
        # Показываем созданные шаблоны
        log_info "Созданные шаблоны доступа:"
        sudo -u postgres psql melsu_db -c "SELECT id, name, access_type, scope, inherit_children FROM directory_access_template WHERE is_active = true ORDER BY id;"
        
        return 0
    else
        log_error "❌ Инициализация завершена с ошибками"
        log_error "Таблиц найдено: $table_count (ожидалось: 2)"
        log_error "Шаблонов создано: $template_count (ожидалось: > 0)"
        return 1
    fi
}

# Функция полного обновления
full_update() {
    log_info "🔄 Начинаю полное обновление системы..."
    
    # Останавливаем сервисы приложения
    systemctl stop melsu-api melsu-worker
    
    # Обновляем проект
    update_project
    
    # Запускаем сервисы
    safe_restart
    
    log_success "✅ Полное обновление завершено!"
}

# Функция мониторинга
monitor_system() {
    echo -e "${BLUE}📊 Мониторинг системы MELSU Portal${NC}"
    echo "=================================="
    
    # Статус сервисов
    echo -e "\n${YELLOW}Статус сервисов:${NC}"
    check_service_status "postgresql"
    check_service_status "redis-server"
    check_service_status "nginx"
    check_service_status "melsu-api"
    check_service_status "melsu-worker"
    
    # Проверка API
    echo -e "\n${YELLOW}Проверка API:${NC}"
    check_api_health
    
    # Проверка БД
    echo -e "\n${YELLOW}База данных:${NC}"
    check_database
    
    # Состояние миграций
    echo -e "\n${YELLOW}Состояние миграций:${NC}"
    cd $BACKEND_PATH
    local current_output=$(sudo -u melsu $BACKEND_PATH/venv/bin/alembic current 2>&1)
    local heads_output=$(sudo -u melsu $BACKEND_PATH/venv/bin/alembic heads 2>&1)
    local heads_count=$(echo "$heads_output" | grep -c "^[a-f0-9]\{12\}")
    
    echo "Текущая ревизия: $(echo "$current_output" | grep -o '[a-f0-9]\{12\}' | head -1 || echo 'не определена')"
    echo "Head ревизия: $(echo "$heads_output" | grep -o '[a-f0-9]\{12\}' | head -1 || echo 'не определена')"
    
    if [ $heads_count -gt 1 ]; then
        echo -e "${RED}⚠️  Конфликт миграций: найдено $heads_count head ревизий${NC}"
    else
        echo -e "${GREEN}✅ Конфликтов миграций не обнаружено${NC}"
    fi
    
    # Использование ресурсов
    echo -e "\n${YELLOW}Использование ресурсов:${NC}"
    echo "CPU: $(top -bn1 | grep "Cpu(s)" | awk '{print $2}' | awk -F'%' '{print $1}')"
    echo "RAM: $(free -h | awk 'NR==2{printf "%.1f%% (используется %s из %s)", $3*100/$2, $3, $2}')"
    echo "Диск: $(df -h / | awk 'NR==2{printf "%s используется из %s (%s)", $3, $2, $5}')"
    
    # Статус Git
    echo -e "\n${YELLOW}Git статус:${NC}"
    cd $PROJECT_PATH
    local current_branch=$(git branch --show-current)
    local last_commit=$(git log -1 --pretty=format:"%h - %s (%cr)")
    echo "Ветка: $current_branch"
    echo "Последний коммит: $last_commit"
    
    # Проверка обновлений
    git fetch origin main > /dev/null 2>&1
    local commits_behind=$(git rev-list --count HEAD..origin/main)
    if [ $commits_behind -gt 0 ]; then
        echo -e "${YELLOW}⚠️  Доступно обновлений: $commits_behind коммитов${NC}"
    else
        echo -e "${GREEN}✅ Проект актуален${NC}"
    fi
}

# Основная функция
main() {
    case "$1" in
        start)
            log_info "🚀 Запуск всех сервисов..."
            systemctl start postgresql redis-server melsu-api melsu-worker nginx
            log_success "✅ Все сервисы запущены"
            ;;
        stop)
            log_info "⏹️ Остановка сервисов приложения..."
            systemctl stop melsu-api melsu-worker
            log_success "⏹️ Сервисы остановлены"
            ;;
        restart)
            log_info "🔄 Перезапуск сервисов..."
            safe_restart
            ;;
        update)
            full_update
            ;;
        migrate)
            apply_migrations
            ;;
        fix-migrations)
            fix_migration_conflicts
            ;;
        diagnose-migrations)
            diagnose_migrations
            ;;
        backup)
            backup_database
            ;;
        status)
            monitor_system
            ;;
        logs)
            echo -e "${BLUE}📋 Логи сервисов (последние 20 строк):${NC}"
            echo "======================================"
            echo -e "\n${YELLOW}API логи:${NC}"
            journalctl -u melsu-api -n 20 --no-pager
            echo -e "\n${YELLOW}Worker логи:${NC}"
            journalctl -u melsu-worker -n 20 --no-pager
            echo -e "\n${YELLOW}Nginx логи:${NC}"
            tail -20 /var/log/nginx/error.log
            ;;
        live-logs)
            echo -e "${BLUE}📋 Мониторинг логов в реальном времени...${NC}"
            journalctl -u melsu-api -u melsu-worker -f
            ;;
        test)
            echo -e "${BLUE}🧪 Тестирование сервисов:${NC}"
            echo "========================"
            echo "Backend API:"
            curl -s -w "Время ответа: %{time_total}s\n" http://localhost:8000/health || echo "API не отвечает"
            echo -e "\nFrontend через Nginx:"
            curl -s -I http://localhost/ | head -1 || echo "Nginx не отвечает"
            echo -e "\nПроверка WebSocket:"
            curl -s -I -H "Upgrade: websocket" http://localhost:8000/ws || echo "WebSocket недоступен"
            ;;
        ssl)
            log_info "🔒 Настройка SSL сертификата..."
            certbot --nginx -d melsu.local -d www.melsu.local
            log_success "🔒 SSL настроен"
            ;;
        deploy)
            log_info "🚀 Запуск полного развертывания..."
            bash /var/www/melsu/deploy.sh
            ;;
        fix-migrations-complete)
            fix_migrations_complete
            ;;
        init-directory-access)
            init_directory_access_system
            ;;
        init)
            log_info "🔄 Полная инициализация системы MELSU Portal..."
            init_directory_access_system
            if [ $? -eq 0 ]; then
                log_info "Перезапуск сервисов после инициализации..."
                safe_restart
                log_success "✅ Система полностью инициализирована и готова к работе!"
            else
                log_error "❌ Ошибка при инициализации системы"
                return 1
            fi
            ;;
        *)
            echo -e "${BLUE}🚀 MELSU Portal - Система управления${NC}"
            echo "====================================="
            echo ""
            echo -e "${YELLOW}Основные команды:${NC}"
            echo "  start       - Запустить все сервисы"
            echo "  stop        - Остановить сервисы приложения"
            echo "  restart     - Перезапустить сервисы"
            echo "  update      - Обновить проект с Git и применить миграции"
            echo "  status      - Показать статус системы"
            echo "  init        - Инициализировать систему управления доступом к справочникам"
            echo ""
            echo -e "${YELLOW}Управление БД:${NC}"
            echo "  migrate              - Применить миграции БД"
            echo "  fix-migrations       - Исправить конфликты миграций"
            echo "  fix-migrations-complete - Полное исправление миграций с очисткой"
            echo "  diagnose-migrations  - Диагностика состояния миграций"
            echo "  backup               - Создать резервную копию БД"
            echo ""
            echo -e "${YELLOW}Мониторинг:${NC}"
            echo "  logs        - Показать последние логи"
            echo "  live-logs   - Мониторинг логов в реальном времени"
            echo "  test        - Тестировать все сервисы"
            echo ""
            echo -e "${YELLOW}Дополнительно:${NC}"
            echo "  ssl         - Настроить SSL сертификат"
            echo "  deploy      - Полное развертывание системы"
            echo "  init-directory-access - Инициализировать систему управления доступом к справочникам"
            echo ""
            echo -e "${GREEN}Примеры использования:${NC}"
            echo "  melsu init                      # Инициализировать систему управления доступом"
            echo "  melsu update                    # Обновить проект"
            echo "  melsu status                    # Проверить статус"
            echo "  melsu fix-migrations            # Исправить конфликты миграций"
            echo "  melsu fix-migrations-complete   # Полное исправление с очисткой"
            echo "  melsu diagnose-migrations       # Диагностика миграций"
            echo "  melsu live-logs                 # Мониторинг в реальном времени"
            echo "  melsu init-directory-access     # Инициализировать систему управления доступом к справочникам"
            ;;
    esac
}

# Запуск основной функции
main "$@" 