"""Update groups table structure

Revision ID: 2ddf5cda9e97
Revises: ceb15c3bd88f
Create Date: 2025-06-29 19:07:42.453949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ddf5cda9e97'
down_revision: Union[str, None] = 'ceb15c3bd88f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
