"""remove_group_number_from_user_profiles

Revision ID: 509424f4a621
Revises: 5d627d5d37bf
Create Date: 2025-06-29 20:34:43.645197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '509424f4a621'
down_revision: Union[str, None] = '5d627d5d37bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'group_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('group_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
