"""add_faculty_and_department_fields_to_profile

Revision ID: 5974b18ca743
Revises: 59acfe778956
Create Date: 2025-07-04 16:19:01.446387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5974b18ca743'
down_revision: Union[str, None] = '59acfe778956'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('faculty_id', sa.Integer(), nullable=True))
    op.add_column('user_profiles', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_profiles', 'departments', ['department_id'], ['id'])
    op.create_foreign_key(None, 'user_profiles', 'departments', ['faculty_id'], ['id'])
    op.drop_column('user_profiles', 'faculty')
    op.drop_column('user_profiles', 'department')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('department', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('faculty', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_profiles', type_='foreignkey')
    op.drop_constraint(None, 'user_profiles', type_='foreignkey')
    op.drop_column('user_profiles', 'department_id')
    op.drop_column('user_profiles', 'faculty_id')
    # ### end Alembic commands ###
