"""remove_group_number_field_from_user_profiles

Revision ID: 5d627d5d37bf
Revises: d81c3bde0d93
Create Date: 2025-06-29 20:34:06.867020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d627d5d37bf'
down_revision: Union[str, None] = 'd81c3bde0d93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'course')
    op.drop_column('groups', 'semester')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('semester', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('groups', sa.Column('course', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
