"""add_status_to_reports

Revision ID: 68ffc49dcdbf
Revises: 9d907fd9995a
Create Date: 2025-06-30 01:02:17.646384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68ffc49dcdbf'
down_revision: Union[str, None] = '9d907fd9995a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавляем колонку как nullable с default значением
    op.add_column('reports', sa.Column('status', sa.String(length=50), nullable=True))
    
    # Обновляем существующие записи
    op.execute("UPDATE reports SET status = 'submitted' WHERE status IS NULL")
    
    # Делаем колонку NOT NULL
    op.alter_column('reports', 'status', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'status')
    # ### end Alembic commands ###
