"""create_directory_access_tables

Revision ID: 807af6accf0a
Revises: b81b44197c01
Create Date: 2025-07-05 19:30:50.142383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '807af6accf0a'
down_revision: Union[str, None] = 'b81b44197c01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directory_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('access_type', sa.Enum('READ', 'WRITE', 'ADMIN', name='accesstype'), nullable=False),
    sa.Column('scope', sa.Enum('STUDENTS', 'GROUPS', 'DEPARTMENTS', 'ALL', name='accessscope'), nullable=False),
    sa.Column('inherit_children', sa.Boolean(), nullable=False),
    sa.Column('restrictions', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('granted_by', sa.Integer(), nullable=True),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_directory_access_department_id'), 'directory_access', ['department_id'], unique=False)
    op.create_index(op.f('ix_directory_access_id'), 'directory_access', ['id'], unique=False)
    op.create_index(op.f('ix_directory_access_user_id'), 'directory_access', ['user_id'], unique=False)
    op.create_table('directory_access_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('access_type', sa.Enum('READ', 'WRITE', 'ADMIN', name='accesstype'), nullable=False),
    sa.Column('scope', sa.Enum('STUDENTS', 'GROUPS', 'DEPARTMENTS', 'ALL', name='accessscope'), nullable=False),
    sa.Column('inherit_children', sa.Boolean(), nullable=False),
    sa.Column('restrictions', sa.JSON(), nullable=True),
    sa.Column('for_roles', sa.JSON(), nullable=True),
    sa.Column('department_types', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_directory_access_templates_id'), 'directory_access_templates', ['id'], unique=False)
    op.create_index(op.f('ix_directory_access_templates_name'), 'directory_access_templates', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_directory_access_templates_name'), table_name='directory_access_templates')
    op.drop_index(op.f('ix_directory_access_templates_id'), table_name='directory_access_templates')
    op.drop_table('directory_access_templates')
    op.drop_index(op.f('ix_directory_access_user_id'), table_name='directory_access')
    op.drop_index(op.f('ix_directory_access_id'), table_name='directory_access')
    op.drop_index(op.f('ix_directory_access_department_id'), table_name='directory_access')
    op.drop_table('directory_access')
    # ### end Alembic commands ###
