"""add_mask_support_to_fields

Revision ID: a1b2c3d4e5f6
Revises: 15750b119fcb
Create Date: 2025-07-02 21:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = '15750b119fcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add mask support fields to fields table
    op.add_column('fields', sa.Column('mask_enabled', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('fields', sa.Column('mask_type', sa.String(50), nullable=True))
    op.add_column('fields', sa.Column('mask_pattern', sa.Text(), nullable=True))
    op.add_column('fields', sa.Column('mask_placeholder', sa.Text(), nullable=True))
    op.add_column('fields', sa.Column('mask_validation_regex', sa.Text(), nullable=True))
    op.add_column('fields', sa.Column('mask_validation_message', sa.Text(), nullable=True))
    op.add_column('fields', sa.Column('mask_guide', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('fields', sa.Column('mask_keep_char_positions', sa.Boolean(), nullable=False, server_default='false'))
    
    # Add indexes for query optimization
    op.create_index('ix_fields_mask_enabled', 'fields', ['mask_enabled'], unique=False)
    op.create_index('ix_fields_mask_type', 'fields', ['mask_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop indexes
    op.drop_index('ix_fields_mask_type', table_name='fields')
    op.drop_index('ix_fields_mask_enabled', table_name='fields')
    
    # Drop columns
    op.drop_column('fields', 'mask_keep_char_positions')
    op.drop_column('fields', 'mask_guide')
    op.drop_column('fields', 'mask_validation_message')
    op.drop_column('fields', 'mask_validation_regex')
    op.drop_column('fields', 'mask_placeholder')
    op.drop_column('fields', 'mask_pattern')
    op.drop_column('fields', 'mask_type')
    op.drop_column('fields', 'mask_enabled')
    # ### end Alembic commands ### 