"""add_social_media_fields

Revision ID: a7843b1b03ca
Revises: 07e3806a12df
Create Date: 2025-07-03 19:48:49.903129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7843b1b03ca'
down_revision: Union[str, None] = '07e3806a12df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('vk_id', sa.String(length=100), nullable=True))
    op.add_column('user_profiles', sa.Column('telegram_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'telegram_id')
    op.drop_column('user_profiles', 'vk_id')
    # ### end Alembic commands ###
