"""add_media_support_to_announcements

Revision ID: b2c3d4e5f6g7
Revises: a1b2c3d4e5f6
Create Date: 2025-07-02 21:15:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2c3d4e5f6g7'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add media support fields to announcements table
    op.add_column('announcements', sa.Column('has_media', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('announcements', sa.Column('media_type', sa.String(20), nullable=True))
    op.add_column('announcements', sa.Column('media_url', sa.String(500), nullable=True))
    op.add_column('announcements', sa.Column('media_filename', sa.String(255), nullable=True))
    op.add_column('announcements', sa.Column('media_size', sa.BigInteger(), nullable=True))
    op.add_column('announcements', sa.Column('media_duration', sa.Integer(), nullable=True))
    op.add_column('announcements', sa.Column('media_thumbnail_url', sa.String(500), nullable=True))
    op.add_column('announcements', sa.Column('media_width', sa.Integer(), nullable=True))
    op.add_column('announcements', sa.Column('media_height', sa.Integer(), nullable=True))
    op.add_column('announcements', sa.Column('media_autoplay', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('announcements', sa.Column('media_loop', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('announcements', sa.Column('media_muted', sa.Boolean(), nullable=False, server_default='true'))
    
    # Add indexes for query optimization
    op.create_index('ix_announcements_has_media', 'announcements', ['has_media'], unique=False)
    op.create_index('ix_announcements_media_type', 'announcements', ['media_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop indexes
    op.drop_index('ix_announcements_media_type', table_name='announcements')
    op.drop_index('ix_announcements_has_media', table_name='announcements')
    
    # Drop columns
    op.drop_column('announcements', 'media_muted')
    op.drop_column('announcements', 'media_loop')
    op.drop_column('announcements', 'media_autoplay')
    op.drop_column('announcements', 'media_height')
    op.drop_column('announcements', 'media_width')
    op.drop_column('announcements', 'media_thumbnail_url')
    op.drop_column('announcements', 'media_duration')
    op.drop_column('announcements', 'media_size')
    op.drop_column('announcements', 'media_filename')
    op.drop_column('announcements', 'media_url')
    op.drop_column('announcements', 'media_type')
    op.drop_column('announcements', 'has_media')
    # ### end Alembic commands ### 