"""add_faculty_and_department_id_fields

Revision ID: d34404f8ec53
Revises: 5974b18ca743
Create Date: 2025-07-04 16:47:30.970109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd34404f8ec53'
down_revision: Union[str, None] = '5974b18ca743'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('faculty_id', sa.Integer(), nullable=True))
    op.add_column('user_profiles', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_user_profiles_faculty', 'user_profiles', 'departments', ['faculty_id'], ['id'])
    op.create_foreign_key('fk_user_profiles_department', 'user_profiles', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_profiles_department', 'user_profiles', type_='foreignkey')
    op.drop_constraint('fk_user_profiles_faculty', 'user_profiles', type_='foreignkey')
    op.drop_column('user_profiles', 'department_id')
    op.drop_column('user_profiles', 'faculty_id')
    # ### end Alembic commands ###
