"""remove_course_semester_from_groups

Revision ID: d81c3bde0d93
Revises: 2ddf5cda9e97
Create Date: 2025-06-29 19:23:58.668969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd81c3bde0d93'
down_revision: Union[str, None] = '2ddf5cda9e97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
