name: 🚀 MELSU Portal Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ closed ]

env:
  PROJECT_PATH: "/var/www/melsu"
  BACKEND_PATH: "/var/www/melsu/backend"
  FRONTEND_PATH: "/var/www/melsu/frontend"

jobs:
  deploy:
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: 🔄 Deploy to Production Server
    
    steps:
    - name: 📝 Checkout code
      uses: actions/checkout@v4
      
    - name: 🚀 Deploy to Server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          set -e
          
          echo "🚀 Начинаю развертывание MELSU Portal..."
          
          # ====================
          # 1. ПОДГОТОВКА
          # ====================
          echo "📋 Этап 1: Подготовка..."
          
          cd ${{ env.PROJECT_PATH }}
          
          # Создаем резервную копию БД
          echo "💾 Создание резервной копии БД..."
          sudo mkdir -p /var/backups/melsu
          BACKUP_FILE="/var/backups/melsu/backup_$(date +%Y%m%d_%H%M%S).sql"
          sudo -u postgres pg_dump melsu_db > "$BACKUP_FILE" 2>/dev/null || echo "БД не найдена, продолжаем..."
          
          # Исправляем права доступа
          echo "🔧 Проверка прав доступа..."
          sudo chown -R melsu:melsu ${{ env.PROJECT_PATH }} || {
            echo "Создание пользователя melsu..."
            sudo useradd -m -s /bin/bash melsu || true
            sudo chown -R melsu:melsu ${{ env.PROJECT_PATH }}
          }
          
          # ====================
          # 2. ОБНОВЛЕНИЕ КОДА
          # ====================
          echo "📦 Этап 2: Обновление кода..."
          
          # Останавливаем сервисы
          echo "⏹️  Остановка сервисов..."
          sudo systemctl stop melsu-api melsu-worker || true
          
          # Обновляем код
          echo "⬇️  Получение обновлений..."
          git stash --include-untracked || true
          git fetch origin main || {
            echo "Переинициализация репозитория..."
            git remote set-url origin https://github.com/sanumxxx/melsu_portal.git
            git fetch origin main
          }
          git reset --hard origin/main
          
          # ====================
          # 3. BACKEND
          # ====================
          echo "🐍 Этап 3: Обновление Backend..."
          
          cd ${{ env.BACKEND_PATH }}
          
          # Создаем/обновляем виртуальное окружение
          if [ ! -d "venv" ]; then
            echo "Создание виртуального окружения..."
            sudo -u melsu python3 -m venv venv
          fi
          
          # Устанавливаем зависимости
          echo "📦 Установка Python зависимостей..."
          sudo -u melsu venv/bin/pip install --upgrade pip
          sudo -u melsu venv/bin/pip install -r requirements.txt
          
          # Применяем миграции
          echo "🗄️  Применение миграций БД..."
          
          # Проверяем количество head ревизий
          HEADS_COUNT=$(sudo -u melsu venv/bin/alembic heads 2>/dev/null | grep -c "^[a-f0-9]\{12\}" || echo "0")
          
          if [ "$HEADS_COUNT" -gt 1 ]; then
            echo "⚠️  Найдено конфликтов миграций: $HEADS_COUNT heads. Исправляю..."
            sudo -u melsu venv/bin/alembic merge heads -m "Auto merge conflicts" || true
          fi
          
          # Применяем миграции
          sudo -u melsu venv/bin/alembic upgrade head || {
            echo "❌ Ошибка применения миграций, проверяю состояние БД..."
            
            # Проверяем, существует ли таблица departments
            DB_CHECK=$(sudo -u postgres psql melsu_db -c "SELECT to_regclass('departments');" -t 2>/dev/null | tr -d ' ')
            
            if [ "$DB_CHECK" = "departments" ]; then
              echo "🔧 Таблицы уже существуют, устанавливаю правильную ревизию..."
              
              # Определяем последнюю ревизию
              LATEST_REV=$(ls -1 alembic/versions/*.py | tail -1 | grep -o '[a-f0-9]\{12\}' | head -1)
              if [ -n "$LATEST_REV" ]; then
                echo "Устанавливаю ревизию: $LATEST_REV"
                sudo -u melsu venv/bin/alembic stamp $LATEST_REV
              fi
            else
              echo "🆕 Создание структуры БД..."
              sudo -u melsu venv/bin/alembic upgrade head
            fi
          }
          
          # ====================
          # 4. FRONTEND
          # ====================
          echo "🌐 Этап 4: Сборка Frontend..."
          
          cd ${{ env.FRONTEND_PATH }}
          
          # Проверяем Node.js
          if ! command -v node &> /dev/null || [ "$(node --version | cut -d'v' -f2 | cut -d'.' -f1)" -lt "18" ]; then
            echo "📦 Обновление Node.js..."
            curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
            sudo apt-get install -y nodejs
          fi
          
          # Устанавливаем зависимости
          echo "📦 Установка npm зависимостей..."
          sudo -u melsu npm ci || sudo -u melsu npm install
          
          # Собираем проект
          echo "🔨 Сборка проекта..."
          sudo -u melsu npm run build
          
          # ====================
          # 5. ПЕРЕЗАПУСК СЕРВИСОВ
          # ====================
          echo "🔄 Этап 5: Перезапуск сервисов..."
          
          # Запускаем сервисы
          echo "▶️  Запуск сервисов..."
          sudo systemctl start melsu-api
          sudo systemctl start melsu-worker
          sudo systemctl restart nginx
          
          # Ждем запуска
          sleep 10
          
          # ====================
          # 6. ПРОВЕРКА
          # ====================
          echo "✅ Этап 6: Проверка работоспособности..."
          
          # Проверяем статус сервисов
          echo "🔍 Статус сервисов:"
          systemctl is-active melsu-api && echo "✅ melsu-api: активен" || echo "❌ melsu-api: неактивен"
          systemctl is-active melsu-worker && echo "✅ melsu-worker: активен" || echo "❌ melsu-worker: неактивен"
          systemctl is-active nginx && echo "✅ nginx: активен" || echo "❌ nginx: неактивен"
          
          # Проверяем API
          echo "🔍 Проверка API..."
          HEALTH_CHECK=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/health 2>/dev/null || echo "000")
          if [ "$HEALTH_CHECK" = "200" ]; then
            echo "✅ API health check: OK"
          else
            echo "⚠️  API health check: код $HEALTH_CHECK"
            
            # Попытка экстренного перезапуска
            echo "🚨 Экстренный перезапуск API..."
            sudo systemctl restart melsu-api
            sleep 5
            
            HEALTH_CHECK2=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/health 2>/dev/null || echo "000")
            if [ "$HEALTH_CHECK2" = "200" ]; then
              echo "✅ API восстановлен после перезапуска"
            else
              echo "❌ API не отвечает после перезапуска"
              exit 1
            fi
          fi
          
          echo "🎉 Развертывание завершено успешно!"
          echo "📊 Информация о развертывании:"
          echo "   - Коммит: $(git rev-parse --short HEAD)"
          echo "   - Время: $(date)"
          echo "   - Резервная копия: $BACKUP_FILE"
